---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: coredns
  namespace: skate
  labels:
    app: coredns
spec:
  selector:
    matchLabels:
      app: coredns
  template:
    metadata:
      labels:
        app: coredns
    spec:
      hostNetwork: true
      volumes:
      - name: cni
        hostPath:
          path: /var/lib/skate/dns
      containers:
      - name: coredns
        image: ghcr.io/skateco/coredns:1.1.0
        volumeMounts:
        - mountPath: /var/lib/skate/dns
          name: cni
        env:
        - name: CORE_FILE
          value: |
            n-%%node%%.skate:5553 {
            
                bind lo 0.0.0.0
            
                hosts /var/lib/skate/dns/addnhosts
            }
            
            svc.cluster.skate:5053 {
                
                    bind lo
                
                    hosts /var/lib/skate/dns/addnhosts
                
            }
            
            pod.cluster.skate:5053 {
            
                bind lo
            
                gathersrv pod.cluster.skate. {
                  # n-node-1.skate. a-
                  %%gather_srv_list%%
                }
                #forward n-node-1.skate. 10.8.0.1:53
                %%forward_list%%
            
                loadbalance round_robin
            
            }
            .:5053 {
                bind lo 0.0.0.0
                forward . 8.8.8.8
            }

