---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ingress
  namespace: skate
  labels:
    app: nginx-ingress
spec:
  selector:
    matchLabels:
      app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
    spec:
      hostNetwork: true
      volumes:
      - name: ingress
        hostPath:
          path: /var/lib/skate/ingress
      - name: le_storage
        hostPath:
          path: /var/lib/skate/ingress/letsencrypt_storage
      containers:
      - name: nginx
        image: ghcr.io/skateco/nginx-ingress:1.0.2
        volumeMounts:
        - mountPath: /var/lib/skate/ingress
          name: ingress
        - mountPath: /etc/resty-auto-ssl/storage
          name: le_storage
